version: '3.8'
services:
  podcastify-premium-app:
    container_name: podcastify-premium-app
    hostname: podcastify-premium-app
    build: .
    env_file: .env
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - '/app/node_modules'
